### ISSUE TITLE
Causing Wine-TKG and NorthstarProton to instantly crash when installed

### ISSUE THREAD

**Issue by KyleGospo** [ValShaped/rwfus#15]
Not sure what's going on here quite yet. I was intending to use rwfus to allow LatencyFleX and vkBasalt on the Deck and ran into this issue.

A clean install of rwfus with no additional files added to the overlayed fs will cause Wine-TKG and NorthstarProton to crash. [Here's a log file via PROTON_LOG=1](https://github.com/ValShaped/rwfus/files/9669278/steam-1237970.log). This is reproducible and is resolved simply by uninstalling rwfus.

I am using a copy of SteamOS with [Phillip Richter's BTRFS payload](https://gitlab.com/popsulfr/steamos-btrfs) and no other changes.

**Comment by ValShaped** [comment]
Thanks for the report! Does it work when Rwfus is installed but deactivated? (`rwfus -d`)

**Comment by KyleGospo** [comment]
Just checked, I can confirm it works fine when deactivated

**Comment by ValShaped** [comment]
I don't have Titanfall|2, so I can't replicate this locally, nor can I seem to get Proton TKG working with or without Rwfus. I'm not familiar with Proton enough to know what's normal behavior, either.

Once Rwfus 0.4.0 is released addressing #12, I'd love it if you'd re-test. Best case, Rwfus 0.3.0's jank was causing the issue and it goes away. Worst case, Rwfus 0.4.0's shiny new jank doesn't fix it and we'll need to work around the problem.

**Comment by ValShaped** [comment]
Rwfus 0.4.0-pre2 should be representative of the final release. Could you retest with that version?

**Comment by ValShaped** [comment]
As I can't test this, I'm closing as wontfix for now. I don't know if this is still an issue or not.
