### ISSUE TITLE
Rwfus does not always successfully unmount

### ISSUE THREAD

**Issue by ValShaped** [ValShaped/rwfus#18]
As seen in #17, Rwfus sometimes fails to unmount overlays, which causes subsequent mounts to fail.

In practice, this is generally not harmful, but failing systemd units aren't great.

**Comment by dzmitry-kankalovich** [comment]
Is there any way to unmount default directories? I ran `sudo ./rwfus --umount` , but still
```
(deck@steamdeck pacman.d)$ df -T .
Filesystem     Type    1K-blocks  Used Available Use% Mounted on
overlay        overlay   8388608   868   8383456   1% /etc/pacman.d
```

**Comment by dzmitry-kankalovich** [comment]
@ValShaped hm, then seems like it's not possible to cleanly uninstall `rwfusd` if the service never actually started, like in my case? Maybe something worth double-checking.

Also, regarding `/etc` - another suggestion is to (if possible) rename `overlay` to `rwfusd-overlay` (unless `overlay` is the mandatory keyword) as it's easy to mix up with SteamOS as it appears (at least for newbies like myself).

in my case why I was bothering with un-install: I had pacman already configured on a system (factory installed OS), which I verified to work. Then I failed to install `rwfus`, and realized that my prev installed pacman is not working anymore - it wouldn't see the `/etc/pacman.d/gnupg` folder needed to boot up (even though the folder was accessible by direct path if you feed it to `cd`, the 'ls -al` would show nothing in `/etc/pacman.d`). I am not sure how it works overlay-wise, but until I ejected overlay on that `/etc` I couldn't repair pacman. I've no idea how SteamOS-pacman-fwfus thing collide here, but maybe it'll make sense for you. I am rocking a factory-installed Steam Deck so far which I got like a month ago.

**Comment by ValShaped** [comment]
@dzmitry-kankalovich `overlay` is the [filesystem type](https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html).

Regarding being unable to access files in /etc/pacman.d/gnupg; if a file is deleted from an overlay, that file is left untouched in the read-only lower dir (i.e. `/etc/`) and "masked" on the read-writable upper dir (`/var/lib/overlay/etc/upper`). It's possible that /etc/pacman.d/gnupg is present on the root filesystem but not in the overlay. If that's the case, you'll have to unmount the /etc/ overlay and delete the maskfiles in `/var/lib/overlay/etc/upper/pacman.d/gnupg`

**Comment by dzmitry-kankalovich** [comment]
@ValShaped thanks, now it makes sense! I've tried `rwfus -Rr` multiple times but still was left with these dangling overlays. Looking at the source code `perform_remove_all`, I don't see the part that explicitly unmounts those overlays unless I miss something. I suspect you unmount them on service stop, but if the service never started due to another problem (I suspect it's https://github.com/ValShaped/rwfus/issues/12), these overlays were never removed. At least this is my hypothesis.  I'll see if I can extract the log file.

**Comment by ValShaped** [comment]
That might be exactly the problem, I rely on rwfusd --stop to unmount everything, and I didn't know that if the service fails to start, it'll also fail to stop. Makes sense, though. I'll see what I can do about it. #12 should be fixed on the dev branch already, I just haven't marked the issue as closed because it's not tested extensively.

**Comment by ValShaped** [comment]
I've added an unmount_all after each incantation of `service stop`, which should rectify this issue.

**Comment by ValShaped** [comment]
As far as I can tell, this has fixed the issue! I'm closing this for now. If it pops up again, give me a shout.
