### ISSUE TITLE
Issue on installing.

### ISSUE THREAD

**Issue by NickNookNeo** [ValShaped/rwfus#25]
I was attempting to install and this error occurred, I have no idea why.

Rwfus v0.4.0 
Carry Pacman across SteamOS updates!

Rwfus directory: /opt/rwfus
Unit Storage directory: /opt/rwfus/service
Systemd directory: /etc/systemd/system

./rwfus -iI
Loading config file /etc/opt/rwfus.conf
> Base_Directory: "/opt/rwfus"
> Directories: "/usr /etc/pacman.d /var/lib/pacman /var/cache/pacman"
> Mount_Options: "loop,compress"

Creating overlays for /usr /etc/pacman.d /var/lib/pacman /var/cache/pacman:
1. Generating directories
2. Generating disk image
ERROR: /opt/rwfus/rwfus.btrfs appears to contain an existing filesystem (btrfs)
ERROR: use the -f option to force overwrite of /opt/rwfus/rwfus.btrfs
btrfs-progs v6.0
See http://btrfs.wiki.kernel.org for more information.

mount: /opt/rwfus/mount: /opt/rwfus/rwfus.btrfs is already mounted.
Resize device id 1 (/dev/loop0) from 8.00GiB to max
umount: /home/.steamos/offload/opt/rwfus/mount (/dev/loop0) unmounted
3. Generating service
Generating service rwfusd
  script /opt/rwfus/service/rwfusd.sh
  unit   /opt/rwfus/service/rwfusd.service
4. Storing configuration
Storing config file to /etc/opt/rwfus.conf...
-rw-r--r-- 1 root root 574 Jan 24 20:26 /etc/opt/rwfus.conf
5. Copying service to /etc/systemd/system
'/opt/rwfus/service/rwfusd.service' -> '/etc/systemd/system/rwfusd.service'
6. Enabling service unit
Job for rwfusd.service failed because a timeout was exceeded.
See "systemctl status rwfusd.service" and "journalctl -xeu rwfusd.service" for details.
Error when enabling service. See /tmp/rwfus.QCqL.log for information.
Loading config file /etc/opt/rwfus.conf
Config already loaded
Removed "/etc/systemd/system/multi-user.target.wants/rwfusd.service".
Removed "/etc/systemd/system/pacman-cleanup.service".
Adding Rwfus to /home/.steamos/offload/usr/local/bin...
'./rwfus_include/config.sh' -> '/home/.steamos/offload/usr/local/bin/rwfus_include/config.sh'
'./rwfus_include/disk.sh' -> '/home/.steamos/offload/usr/local/bin/rwfus_include/disk.sh'
'./rwfus_include/info.sh' -> '/home/.steamos/offload/usr/local/bin/rwfus_include/info.sh'
'./rwfus_include/manage-install.sh' -> '/home/.steamos/offload/usr/local/bin/rwfus_include/manage-install.sh'
'./rwfus_include/service-main.sh' -> '/home/.steamos/offload/usr/local/bin/rwfus_include/service-main.sh'
'./rwfus_include/service.sh' -> '/home/.steamos/offload/usr/local/bin/rwfus_include/service.sh'
'./rwfus_include/testlog.sh' -> '/home/.steamos/offload/usr/local/bin/rwfus_include/testlog.sh'
'./rwfus' -> '/home/.steamos/offload/usr/local/bin/rwfus'
Created symlink /etc/systemd/system/multi-user.target.wants/rwfusd.service → /etc/systemd/system/rwfusd.service.
Job for rwfusd.service failed because a timeout was exceeded.
See "systemctl status rwfusd.service" and "journalctl -xeu rwfusd.service" for details.
Error when enabling service. See /tmp/rwfus.QCqL.log for information.
Done!

**Comment by ValShaped** [comment]
Rwfus 0.4.0 has a few problems that've been fixed in the Dev branch. Can you retry the install with 0.4.1-beta1?

**Comment by NickNookNeo** [comment]
> Rwfus 0.4.0 has a few problems that've been fixed in the Dev branch. Can you retry the install with [0.4.1-beta1](https://github.com/ValShaped/rwfus/releases/tag/v0.4.1-beta1)?

It all installed correctly except it said failed to initialize keyring or something

**Comment by ValShaped** [comment]
I've had issues with that too, recently. Valve, pls

**Comment by ValShaped** [comment]
@NickNookNeo Have you tried again recently? I was running into similar issues last week, but they seem to be resolved this week. I'm guessing it was something on Valve's end.

**Comment by NickNookNeo** [comment]
> @NickNookNeo Have you tried again recently? I was running into similar issues last week, but they seem to be resolved this week. I'm guessing it was something on Valve's end.

Sorry I'm late but I'm not sure but my stuff doesn't seem to be deleting after updating

**Comment by ValShaped** [comment]
Try doing a `pacman-key --init` and `pacman-key --populate`. It sounds like Rwfus worked, at least.

**Comment by NickNookNeo** [comment]
> Try doing a `sudo pacman-key --init` and `sudo pacman-key --populate`. It sounds like Rwfus worked, at least.

Alright, Just did and haven't had issue since

**Comment by ValShaped** [comment]
Awesome!
