### ISSUE TITLE
installation instructions clone the wrong version.

### ISSUE THREAD

**Issue by gitdunk** [ValShaped/rwfus#27]
I don't really know where else to put this but I just want to notify you that git clone currently downloads the broken 0.4.0 version unless you do `git clone --depth=1 --branch v0.4.1-beta1 https://github.com/ValShaped/rwfus.git` and then it clones the correct version.

**Comment by ValShaped** [comment]
I haven't merged 0.4.1 yet; it's still in prerelease. Guess I should do that now!
