### ISSUE TITLE
Use SteamOS Btrfs subvolumes instead of creating a disk image file

### ISSUE THREAD

**Issue by HeavenVolkoff** [ValShaped/rwfus#28]
Hey,

Great project. Was reading the recent changes, and the current code creates a BTRFS formatted disk image file to store all the overlayfs changes. That is a nice solution for users of the default Steam OS formatted home. However, for people using [SteamOS BTRFS](https://gitlab.com/popsulfr/steamos-btrfs) could it be possible to support using direct subvolumes on the home partition instead. Would you accept a PR for this?

**Comment by ValShaped** [comment]
I think that'd be great!
