### ISSUE TITLE
Question: Remove steam.desktop autostart and boot in desktop mode (Since you're brave to use desktop mode)

### ISSUE THREAD

**Issue by aemonge** [ValShaped/rwfus#31]
So, I'm unbrave enough to simple remove the auto start of steam app at */etc/xdg/autostart/steam.desktop* , being afraid KDE will not launch.

Have you tried to remove this and start the deck directly into desktop mode?

**Comment by ValShaped** [comment]
Works fine, but you'll be stuck with the deck's default controller configuration unless you manually start Steam, which isn't that great imo. I'd suggest leaving it alone, unless you don't want to sign into Steam.

**Comment by aemonge** [comment]
I appreciate a lot to answer me. I do, now, realise I should have asked this at Steam Deck support forum, instead of here. I keep this for Rwfus only from now on.

I great full for the tool, since I'm using the Deck for ML development purposes, so I mess a lot with `pacman` and `pikaur` and with rwfus I can do it saftly <3

**Comment by ValShaped** [comment]
Glad you like it!

I'll warn you though, Rwfus doesn't currently have any safeguards if booting fails because of package incompatibility. Don't update glibc, and you'll be fine, though.
