### ISSUE TITLE
Incompatible with SteamOS 3.5 ('jupiter-main')

### ISSUE THREAD

**Issue by ValShaped** [ValShaped/rwfus#33]
# Summary 
SteamOS 3.5 moved the pacman database from `/var/lib/pacman` to `/usr/lib/holo/pacmandb`.
3.5 has support for the Nix package manager, which covers most, but not all of Rwfus' use-cases, and is reliable.
Due to Rwfus' continued usage, I've decided to continue supporting it into the future.

[Prerelease 0.5.0.b1](https://github.com/ValShaped/rwfus/releases/tag/v0.5.0.b1) has support for SteamOS 3.5, but drops support for SteamOS 3.4 at the moment.

# Original message:
SteamOS 3.5 removes `/var/lib/pacman` from the base image, which breaks rwfus' default config.

Since SteamOS 3.5 also adds support for [installing](https://github.com/DeterminateSystems/nix-installer/) the [`nix` package manager](https://github.com/NixOS/nix), I'm unsure whether to support Rwfus going forward. Nix has most packages that aren't available as a flatpak, and provides consistent dependency management irrespective of the base system, which **absolutely** is not the case with Rwfus.

**Comment by Retidurc** [comment]
Nix packages are kinda like flatpak or appimage then ? Self contained things ?

**Comment by Retidurc** [comment]
The current problem with /var/lib/pacman being absent, is pacman thant pacman want to install dependencies that are already in the system, but fail because of files collision, right ?

**Comment by i-lost-my-bagel** [comment]
there are programs that don't work with nix without some extra configuration though and there's some things that just wouldn't work. 

I use rwfus to have i3 installed and modify the desktop mode switching script so I can use it instead of KDE and I just can't do that with nix.

**Comment by ValShaped** [comment]
@Retidurc Nix packages are run natively, (not containerized or virtualized,) but install to `/nix/store/<package identifier>/*` instead of `/usr/*`.

The problem with /var/lib/pacman not existing is that the directory needs to be present on the filesystem or it's not a valid place to mount things. Rwfus is trying to overlay-mount `/opt/rwfus/mount/var-lib-pacman` onto `/var/lib/pacman`, but if `/var/lib/pacman` doesn't exist it'll assume something went critically wrong and unmount everything.

**Comment by ValShaped** [comment]
@i-lost-my-bagel In that case, I'll figure out if there's a way to keep compatibility. Rwfus has been on the back-burner for a while because, to the best of my knowledge, it's just worked until now. Hopefully, once 3.5 drops, it'll keep working into the future.

I'm a bit confused as to why /var/lib/pacman is reportedly missing on new SteamOS, since /var/ is *supposed* to persist across versions. I haven't had the time this week to jump onto jupiter-main and check it out for myself.

**Comment by Retidurc** [comment]
/var/lib/pacman have been removed from the base image but the steamos-BTRFS guys seems to have found the pacman database still exist, but in another place : /usr/lib/holo/pacmandb

https://gitlab.com/popsulfr/steamos-btrfs/-/issues/69

**Comment by ValShaped** [comment]
This should be fixed in [prerelease v0.5.0.b1](https://github.com/ValShaped/rwfus/releases/tag/v0.5.0.b1). I invite you to give it a try!

**Comment by i-lost-my-bagel** [comment]
> This should be fixed in [prerelease v0.5.0.b1](https://github.com/ValShaped/rwfus/releases/tag/v0.5.0.b1). I invite you to give it a try!

Working great!

![image](https://github.com/ValShaped/rwfus/assets/32345477/eb5cfc18-340d-4dd0-9fbc-fd17f1131cad)

**Comment by ValShaped** [comment]
Awesome! If you run into any problems, let me know, and feel free to reopen this issue. Rwfus 0.5.0 will be in beta until SteamOS 3.5 stabilizes.
