### ISSUE TITLE
Under SteamOS 3.4.11, there is not enough space in /etc to reinstall plasma.

### ISSUE THREAD

**Issue by huangsijun17** [ValShaped/rwfus#40]
Under SteamOS 3.4.11, I hope to reinstall plasma [like this](https://github.com/mengmeet/SteamDeck-LanguageFix) to get the complete language pack, but after installing rwfus, the installation prompt prompts that `/etc` does not have enough space to reinstall plasma.
```
$ sudo pacman -S plasma 
... 
error: Partition /etc too full: 11772 blocks needed, 11771 blocks free 
error: not enough free disk space 
error: failed to commit transaction (not enough free disk space) 
Errors occurred, no packages were upgraded. 
```

**Comment by ValShaped** [comment]
`/etc` contents are preserved across updates, and its overlay is stored in `/var/lib/overlays/etc/upper`. Rwfus stores a config file in `/etc/opt/rwfus.conf` and a log file in `/var/log/rwfus.log`
