### ISSUE TITLE
Running commands from steamos-devmode script breaks rwfus after reboot

### ISSUE THREAD

**Issue by safijari** [ValShaped/rwfus#43]
The `steamos-devmode` script runs the following comments after disabling read-only. I mostly need this in order to restore headers for building packages. When I run this inside rwfus, things work fine until I reboot and then rwfus fails to mount the overlay.
```sudo rm -rf /etc/pacman.d/gnupg/ || :
sudo pacman-key --init
sudo pacman-key --populate
sudo pacman -Sy --noconfirm --needed archlinux-keyring
sudo pacman --noconfirm -S $(pacman -Qnkq | cut -d' ' -f1 | sort | uniq)
sudo pacman -S base-devel multilib-devel --needed
```

**Comment by ValShaped** [comment]
This is a known issue and a wontfix. Unfortunately, Rwfus refuses to mount the overlay to avoid bricking someone's SteamOS install:
https://github.com/ValShaped/rwfus/issues/20
