### ISSUE TITLE
not working??

### ISSUE THREAD

**Issue by itzzjd123** [ValShaped/rwfus#45]
i went through the whole installation and got this error. is this normal??
![image](https://github.com/ValShaped/rwfus/assets/138529607/a54e6afb-a052-4703-8007-652fe519e433)

**Comment by itzzjd123** [comment]
![image](https://github.com/ValShaped/rwfus/assets/138529607/fc00f460-5a00-4b54-84ad-4405d8fd807d)

i dont believe this method works on the OLED steam deck

**Comment by ValShaped** [comment]
Are you using the right version of Rwfus for your version of SteamOS? Rwfus 0.4.x is for SteamOS <3.5; Rwfus 0.5.0 is for SteamOS ≥3.5

Also, please post your `/etc/opt/rwfus.log` file.

**Comment by itzzjd123** [comment]
![image](https://github.com/ValShaped/rwfus/assets/138529607/d13856f3-323b-45fa-b454-e012c3810a1d)

**Comment by itzzjd123** [comment]
where is the rwfus.log??

**Comment by itzzjd123** [comment]
![image](https://github.com/ValShaped/rwfus/assets/138529607/528b62ad-3852-4dfb-9347-7283e2530e23)

**Comment by itzzjd123** [comment]
Sorry man im new to this. So do Ihave todownload the latest release? I thought there was code for the steam deck to install the latest release. Im stumped.

**Comment by ValShaped** [comment]
Don't panic, everything's gonna be fine. I think you cloned the current `main` branch. I got the path wrong for rwfus.log, sorry, it's `/var/log/rwfus.log`

To switch to version 0.5.0, you can run `git checkout "v0.5.0"` and run `./rwfus -i` to upgrade to it. Or, you can download the latest release .zip, rwfus v0.5.0.b1, from the releases page. They're equivalent.

**Comment by itzzjd123** [comment]
sweet thanks man i will try in a minute then will let you know if i got it thanks!

**Comment by itzzjd123** [comment]
Hello sorry I nowhave time for it. So I ran the code you gave me and it sid that its been updated and now when i go to install Chaotic-Aur I get an error. 

![image](https://github.com/ValShaped/rwfus/assets/138529607/57fb2452-9cf0-43e7-b7dc-195aac86997b)

**Comment by itzzjd123** [comment]
@ValShaped

**Comment by itzzjd123** [comment]
[rwfus.log](https://github.com/ValShaped/rwfus/files/13699127/rwfus.log)

**Comment by itzzjd123** [comment]
![image](https://github.com/ValShaped/rwfus/assets/138529607/2045e85f-ece3-40d3-88bc-e611bdae13be)

Still wontchange it up ive tried a lot please help whenever you have time thanks.

![image](https://github.com/ValShaped/rwfus/assets/138529607/481342a3-11f9-4c96-9b17-589fa026a290)

**Comment by ValShaped** [comment]
The logfile is append-only—new entries are added on to the end. I've read your logfile, and Rwfus is working. You can verify by running
```sh
./rwfus
```
it will print information about your rwfus install.

I've never used Chaotic-Aur before, so I can't confirm whether or not it should work.

**Comment by itzzjd123** [comment]
Okay so is everything after the rwfus install optional then or do I need anything else to capture my screen on obs. I am wanting it to work on my steam deck game mode.

**Comment by ValShaped** [comment]
I have no idea; I didn't have a hand in making the guide you're following, nor have I followed it myself.
Rwfus doesn't know anything about what you install inside it, for the most part. It starts up early in the boot process, mounts some things, and gets out of the way until you disable it or shut down the Deck.

**Comment by itzzjd123** [comment]
![image](https://github.com/ValShaped/rwfus/assets/138529607/654d73d6-8868-42b0-ab7d-817356ab5df6)

This is what i get when i run the command

**Comment by ValShaped** [comment]
You have to do it from within the directory you clones Rwfus into (hence the `./`)

**Comment by mzzfederico** [comment]
I had the same issue but switching to the branch did the job:

```bash
(deck@steamdeck rwfus)$ git checkout "v0.5.0"
branch 'v0.5.0' set up to track 'origin/v0.5.0'.
Switched to a new branch 'v0.5.0'
(deck@steamdeck rwfus)$ ./rwfus --install 
This command must be performed as root
Rwfus 0.5.0.b1 is only compatible with SteamOS 3.5
Are you sure you want to install Rwfus 0.5.0.b1? [y|N] y
Creating overlays for /usr /etc/pacman.d /var/cache/pacman:
0. Disabling service
1. Creating directories...
2. Updating disk image...
3. Generating service...
4. Storing configuration...
5. Copying service to /etc/systemd/system
6. Enabling service unit
7. Setting up pacman...
Done!

● rwfusd.service - Rwfus: Carry Pacman across SteamOS updates!
     Loaded: loaded (/etc/systemd/system/rwfusd.service; enabled; preset: disabled)
     Active: active (exited) since Fri 2024-03-08 18:16:35 CET; 23s ago
    Process: 96999 ExecStart=/opt/rwfus/service/rwfusd.sh --start (code=exited, status=0/SUCCESS)
   Main PID: 96999 (code=exited, status=0/SUCCESS)
        CPU: 178ms
Log saved to /var/log/rwfus.log
```

Nice work btw! This is super useful.

**Comment by Lanklow** [comment]
I'm still getting this error (on 3.5) every time after the 'verifying installation' message shows on boot... Even changing the branch does not help... Uninstalling/reinstalling has been the only workaround.

**Comment by ValShaped** [comment]
@Lanklow I'm unable to reproduce on my Deck. What packages do you have installed in the overlay?

**Comment by Lanklow** [comment]
> @Lanklow I'm unable to reproduce on my Deck (Stable, 3.5.19) What packages do you have installed in the overlay?
> 
> Also, could you post `/var/log/rwfus.log` and the output of
> 
> ```shell
> journalctl -xeu rwfusd
> ```

Thanks for your quick reply...  For some reason, it actually started working again after a couple re-installs...

If I run into it again, I can post the log... Now that it's working, I don't see the use in sending it...

Appreciate the tool! It's so nice being able to use the SD like a normal Arch install.

**Comment by ValShaped** [comment]
Thanks! I just remembered though: installing the `glibc` package in the overlay will break your install. Rwfus is hardcoded to look for that package specifically on bootup and immediately unmount if it's present in the overlay. ( Issue #20 )

When Valve updates SteamOS, they rebuild all the packages with the latest glibc. Having an older version in the overlay will cause linker failures pretty much across the board, and put your Deck in a nearly-inoperable state.

**Comment by Lanklow** [comment]
> Thanks! I just remembered though: installing the `glibc` package in the overlay will break your install. Rwfus is hardcoded to look for that package specifically on bootup and immediately unmount if it's present in the overlay. ( Issue #20 )
> 
> When Valve updates SteamOS, they rebuild all the packages with the latest glibc. Having an older version in the overlay will cause linker failures pretty much across the board, and put your Deck in a nearly-inoperable state.

I just installed Tailscale and Syncthing. Thank you for the tip. I'll make sure to keep glibc out of the picture!
